### ISSUE TITLE
babel repl doesnt work

### ISSUE THREAD

**Issue by felipe-coelho** [t-sauer/vscode-babel-repl#1]
Im using VS Code 1.9.1, i installed the babel repl, open the pallet commmand, search for babel, press enter but nothing happens.

**Comment by t-sauer** [comment]
I just pushed a fix for it. I will publish it soon.

Edit: It's published. If you still have any problems let me know.

**Comment by sap-moneytree** [comment]
nothing happens on pressing enter

**Comment by zfrisch** [comment]
I still have this issue as well.
